spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/management
  flyway:
    url: jdbc:postgresql://localhost:5432/management
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    exchanges:
      file-events: file.events
      file-events-dlx: file.events.dlx
    queues:
      file-processing: file.processing
      file-processing-dlq: file.processing.dlq
    routing:
      file-uploaded: file.uploaded
      file-processing-started: file.processing.started
      file-processing-completed: file.processing.completed
      file-processing-failed: file.processing.failed

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: secure-media-vault
