name: 🚀 Deploy

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-staging:
    name: 🚀 Deploy to Staging
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'staging' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-'))
    environment:
      name: staging
      url: https://staging-secure-media-vault.example.com
    
    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4

    - name: 🔐 Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: 🐳 Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 🏷️ Extract version
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: 📝 Create deployment manifest
      run: |
        envsubst < k8s/staging/deployment.yaml > deployment-staging.yaml
      env:
        IMAGE_TAG: ${{ steps.version.outputs.version || 'latest' }}
        DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
        REDIS_URL: ${{ secrets.STAGING_REDIS_URL }}
        RABBITMQ_URL: ${{ secrets.STAGING_RABBITMQ_URL }}
        MINIO_URL: ${{ secrets.STAGING_MINIO_URL }}

    - name: 🚀 Deploy to EKS
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
        kubectl apply -f deployment-staging.yaml
        kubectl rollout status deployment/secure-media-vault-staging -n staging
        kubectl get services -n staging

    - name: 🔍 Health Check
      run: |
        STAGING_URL="${{ secrets.STAGING_URL }}"
        for i in {1..30}; do
          if curl -f $STAGING_URL/actuator/health; then
            echo "✅ Staging deployment healthy"
            exit 0
          fi
          echo "Waiting for deployment to be ready... ($i/30)"
          sleep 10
        done
        echo "❌ Staging deployment failed health check"
        exit 1

    - name: 🧪 Run Smoke Tests
      run: |
        chmod +x ./scripts/smoke-tests.sh
        ./scripts/smoke-tests.sh ${{ secrets.STAGING_URL }}

  deploy-production:
    name: 🚀 Deploy to Production
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-'))
    environment:
      name: production
      url: https://secure-media-vault.example.com
    needs: [deploy-staging]
    
    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4

    - name: 🔐 Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: 🐳 Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 🏷️ Extract version
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: 📝 Create deployment manifest
      run: |
        envsubst < k8s/production/deployment.yaml > deployment-production.yaml
      env:
        IMAGE_TAG: ${{ steps.version.outputs.version }}
        DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
        REDIS_URL: ${{ secrets.PRODUCTION_REDIS_URL }}
        RABBITMQ_URL: ${{ secrets.PRODUCTION_RABBITMQ_URL }}
        MINIO_URL: ${{ secrets.PRODUCTION_MINIO_URL }}

    - name: 🚀 Deploy to EKS with Blue-Green strategy
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
        
        # Deploy to green environment
        kubectl apply -f deployment-production.yaml
        kubectl rollout status deployment/secure-media-vault-green -n production
        
        # Health check green environment
        kubectl port-forward service/secure-media-vault-green 8080:8080 -n production &
        sleep 10
        
        if curl -f http://localhost:8080/actuator/health; then
          echo "✅ Green deployment healthy, switching traffic"
          kubectl patch service secure-media-vault-production -n production -p '{"spec":{"selector":{"version":"green"}}}'
          kubectl delete deployment secure-media-vault-blue -n production --ignore-not-found=true
          kubectl get services -n production
        else
          echo "❌ Green deployment failed health check, rolling back"
          kubectl delete deployment secure-media-vault-green -n production
          exit 1
        fi

    - name: 🔍 Production Health Check
      run: |
        PRODUCTION_URL="${{ secrets.PRODUCTION_URL }}"
        for i in {1..30}; do
          if curl -f $PRODUCTION_URL/actuator/health; then
            echo "✅ Production deployment healthy"
            exit 0
          fi
          echo "Waiting for deployment to be ready... ($i/30)"
          sleep 10
        done
        echo "❌ Production deployment failed health check"
        exit 1

    - name: 🧪 Run Production Smoke Tests
      run: |
        chmod +x ./scripts/smoke-tests.sh
        ./scripts/smoke-tests.sh ${{ secrets.PRODUCTION_URL }}

    - name: 📊 Update Monitoring
      run: |
        # Update monitoring dashboards and alerts
        echo "Updating production monitoring for version ${{ steps.version.outputs.version }}"

    - name: 🎉 Notify Success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: "🎉 Production deployment successful! Version ${{ steps.version.outputs.version }} is now live."
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: 🚨 Notify Failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        text: "🚨 Production deployment failed! Version ${{ steps.version.outputs.version }}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
